### ISSUE TITLE
Please provide a description: How to use aws-sdk-typescript.

### ISSUE THREAD

**Issue by JanOschii** [ingenieux/aws-sdk-typescript#16] opened 2016-07-06 16:15 UTC
As a beginner, i still have some questions. Some words in the readme would be nice, about:
- I do not need to install the aws-sdk anymore, do I?
- I do not need to install the typings for aws-sdk anymore, right?
- How I "require" the library in my project

I think that could help a lot of people.

Thank you

Jan

**Comment by aldrinleal** [comment] 2016-07-06 16:44
Pull Requests are welcome!

**Comment by jabrythehutt** [comment] 2016-07-06 20:10
@JanOschii 
1. You still need to install the aws-sdk module since this project is only there to provide the typescript bindings
2. You should not install the definitely typed bindings if you use this version
3. You can use these in your project by setting up [typings](https://github.com/typings/typings) and then installing the bindings from github using: 
   `typings i aws-sdk=github:ingenieux/aws-sdk-typescript#HEAD --save -G`

If your setup is correct then you should be able to use a standard import or require statement in your code e.g.
`import {S3} from "aws-sdk";`

@aldrinleal I've started a readme in my forked version with installation instructions

**Comment by JanOschii** [comment] 2016-07-07 08:28
@djabry Many thanks m8! That really helps starting using aws-sdk-typescript.

**Comment by DmitryEfimenko** [comment] 2016-08-12 05:15
these aws typings are so much better then the once on DefinitellyTyped.
I was looking for a way to install them using `typings`, and the comment by @djabry worked great, but on a relevant note, how come these typings are not coming up when you `typings search aws-sdk`?
I bet if more people were aware of them, it would only help!

**Comment by Prashant-Kan** [comment] 2016-08-14 12:51
I am facing the issue using the aws.sdk.ts file. I have install it and import in my mainmodule.ts file. 
Have used S3bucket, config and other functions from aws.sdk file. But, when I run in the browser It shows undefined for the aws import file.

`import * as AWS from 'aws-sdk';`

```
export function typeScriptViewModel(first, last) {
    var self = this;
    var DataBucket = 'emaildataports';
    var userDatBucket = 'user-data';

    var testBucket = 'emailtests';
    var userTestBucket = 'user--tests';


    AWS.Config({
        accessKeyId: 'myaccessKeyID',
        secretAccessKey: 'mysecretAccessKey'
    });
....
...
...
// many more usage of AWS. but got stuck on the first implementation itself.
   //var bucket = new AWS.S3({
   //         params: {
   //             Bucket: bucketName, Prefix: path, Delimiter: '/'
   //         }
   //     });
}
```

"Uncaught TypeError: Cannot read property 'Config' of undefined".

what can be the solution for this. 
I read the comment to install the typings and go ahead. But, didn't able to get on that. Getting error when installing using
`typings i aws-sdk=github:ingenieux/aws-sdk-typescript#HEAD --save -G`

I have typings folder in my root project. I know I m missing some minor thing.

**Comment by jabrythehutt** [comment] 2016-08-14 13:51
@Prashant-Kan - It's difficult to tell from your code what's going wrong since it's probably a configuration issue (i.e. something with your package.json or with your index.html). Are you able to recreate the problem on Codepen or something similar?

if AWS is undefined then it would suggest that the AWS SDK isn't installed - you could try `npm install --save aws-sdk`

**Comment by Prashant-Kan** [comment] 2016-08-14 14:22
I was trying to follow your previous comments on 7th July. 
and now also tried to install the aws-sdk. Facing the attached error.
Kindly check and reply if you have the solution. Meanwhile I will upload the code to codepen or fiddler for you to check.

![npm_aws](https://cloud.githubusercontent.com/assets/17109022/17649676/60d953f2-6258-11e6-8d2c-8b55c98219b4.jpg)

Thanks in advance

**Comment by Prashant-Kan** [comment] 2016-08-14 19:28
@djabry 
I have share the visual studio source for you.
I can't share via codepen or fiddle. So in the end I have share using gmail drive. Hope you reproduce the error and revert with some solution. I have send you the link in your email.

IGNORE the above comments
Ok. Wil share into github.

**Comment by aldrinleal** [comment] 2016-08-14 19:34
@Prashant-Kan its better to have your code into gist (gist.github.com)

**Comment by Prashant-Kan** [comment] 2016-08-14 20:01
Hi,
I have created one new repository [ https://github.com/Prashant-Kan/AwsDemo]. Kindly check and let me know if anything missing.

**Comment by jabrythehutt** [comment] 2016-08-15 09:32
@Prashant-Kan - It looks like you're using the definitely typed version of the AWS SDK Typescript bindings (rather than the one associated with ingenieux/aws-sdk-typescript): https://github.com/Prashant-Kan/AwsDemo/blob/master/awsdemo/Scripts/typings/aws-sdk/aws-sdk.d.ts 

Also: I can't see any error messages in your screenshot so I'm not sure what could be causing your problems.

If the error you're getting is that AWS is not defined then the problem in your project is going to be with how you import the AWS SDK rather than with how you reference the Typescript bindings i.e. something to do with how you're using requirejs to load the AWS SDK.

One thing you could try is just adding `<script src="https://sdk.amazonaws.com/js/aws-sdk-2.5.0.min.js"></script>` to your index.html instead of using requirejs.

I'm afraid I can't help with the Visual studio configuration part of your project since I'm not familiar with it and don't have a Windows machine.

**Comment by aldrinleal** [comment] 2016-08-15 10:33
So basically its unrelated. Please note that:

a. You didn't open a new issue
b. You didn't do your homework and posted the issue on the wrong project
c. Its completely unrelated to how aws-sdk-typescript

So please review your manners, really.

(btw, I'm closing this)

**Closed as completed by aldrinleal** 2016-08-15 10:33 UTC
